import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { Container, Card, Alert, Spinner } from 'react-bootstrap';

const AIFeedbackPage = () => {
  const { examId } = useParams();
  const [feedbackText, setFeedbackText] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    setLoading(true);
    setError(null);
    // Placeholder for real fetch logic
    setTimeout(() => {
      setFeedbackText('Sample AI feedback will appear here...');
      setLoading(false);
    }, 1000);
  }, [examId]);

  if (loading) {
    return (
      <div className="text-center my-5">
        <Spinner animation="border" />
        <p>Generating AI feedback...</p>
      </div>
    );
  }

  if (error) {
    return (
      <Container className="mt-4">
        <Alert variant="danger">
          <strong>Error:</strong> {error}
        </Alert>
      </Container>
    );
  }

  return (
    <Container className="mt-4">
      <Card className="shadow-sm mb-4">
        <Card.Header className="bg-primary text-white">
          <h4>AI-Generated Teaching Feedback</h4>
          <span className="small">Exam ID: {examId}</span>
        </Card.Header>
        <Card.Body>
          <pre style={{ whiteSpace: 'pre-wrap', fontFamily: 'inherit' }}>
            {feedbackText}
          </pre>
        </Card.Body>
      </Card>
      <Alert variant="info">
        <i className="bi bi-robot"></i> Feedback is generated by AI.
      </Alert>
    </Container>
  );
};

export default AIFeedbackPage;
